steps:
- name: justinsb/git-fingerprint

- name: gcr.io/cloud-builders/bazel
  args: ['version']

- name: gcr.io/cloud-builders/bazel
  args: ['build', '//cmd/...', '//images:etcd-manager', '//images:etcd-backup', '//images:etcd-dump']
  # To build with GCS cache
  #args: ['build', '--google_default_credentials', '--spawn_strategy=remote', '--genrule_strategy=remote', '--strategy=Javac=remote', '--strategy=Closure=remote', '--remote_http_cache=https://storage.googleapis.com/cache-bucket', '//cmd/...']

# Temporary removed
#- name: gcr.io/cloud-builders/bazel
#  args: ['test', '//test/...', '--test_output=streamed', '--local_test_jobs=1']

- name: debian:stretch
  args: ['mkdir', '-p', 'staging/ctl']

- name: debian:stretch
  args: ['cp', 'bazel-bin/cmd/etcd-manager/linux_amd64_stripped/etcd-manager', 'staging/']
- name: debian:stretch
  args: ['cp', 'bazel-bin/cmd/etcd-manager-ctl/linux_amd64_stripped/etcd-manager-ctl', 'staging/ctl/']

artifacts:
  objects:
    location: 'gs://$_GCS_LOCATION/$REPO_NAME/$COMMIT_SHA'
    #paths: ['bazel-bin/cmd/etcd-manager-ctl/linux_amd64_stripped/etcd-manager-ctl', 'bazel-bin/cmd/etcd-manager/linux_amd64_stripped/etcd-manager']
    paths: ['staging/**']

timeout: 1800s
options:
  machineType: N1_HIGHCPU_8
  requestedVerifyOption: VERIFIED
  sourceProvenanceHash: [ "SHA256" ]
